- name: Create .git directory
  ansible.builtin.file:
    path: "~/.git"
    state: directory
    mode: "0700"

- name: Copy commit template
  ansible.builtin.template:
    src: "git.commit-template"
    dest: "~/.git/commit-template"
    mode: "0600"

- name: Register commit template
  community.general.git_config:
    scope: global
    name: commit.template
    value: "~/.git/commit-template"
