- name: Setup dircolors
  ansible.builtin.template:
    src: "dir_colors"
    dest: "~/.dir_colors"
    mode: "0600"

- name: Setup vim configuration
  ansible.builtin.template:
    src: "vimrc"
    dest: "~/.vimrc"
    mode: "0600"

- name: Setup ZSH configuration
  ansible.builtin.template:
    src: "zshrc"
    dest: "~/.zshrc"
    mode: "0600"

- name: Setup Git VCS
  ansible.builtin.include_tasks: git.yaml
