- name: Install brew packages
  community.general.homebrew:
    name:
      - "ansible"           # ansible tool itself
      - "ansible-lint"      # linter for ansible
      - "coreutils"         # dir_colors & other shell utilities
      - "elixir"            # Elixir programming language
      - "git"               # Git VCS
      - "hugo"              # Hugo website builder
      - "mas"               # Mac App Store
      - "n"                 # NPM manager
      - "p7zip"             # 7z extractor for encrypted files
      - "sbt"               # Package manager for Scala
    state: present
    update_homebrew: true

- name: Install brew packages from cask
  community.general.homebrew_cask:
    name:
      - "backblaze"                 # Backup software
      - "blender"                   # 3D modeling suite
      - "docker"                    # Linux containers' platform
      - "gpg-suite-no-mail"         # GPG keys management CLI + UI
      - "jetbrains-toolbox"         # JetBrains IDE manager
      - "krita"                     # Drawing tool
      - "logi-options-plus"         # Logitech mouse drivers
      - "logitech-camera-settings"  # Logitech camera drivers
      - "mactex"                    # LaTeX for MacOSX
      - "netnewswire"               # RSS reader
      - "obs"                       # Screen recorder
      - "skype"                     # Skype web calling software
      - "sublime-text"              # Simple text editor
      - "temurin@11"                # OpenJDK - LTS
      - "temurin@21"                # OpenJDK - latest
      - "texmaker"                  # LaTeX IDE
      - "vlc"                       # Video player
      - "yubico-authenticator"      # YubiKey software - authenticator
      - "yubico-yubikey-manager"    # YubiKey software - key manager
    state: present
